version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 034362040556.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=034362040556.dkr.ecr.us-east-1.amazonaws.com/myfirstecr
      - echo "Repository URI is $REPOSITORY_URI"
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t hello-world .
      - docker tag hello-world:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
      - docker push $REPOSITORY_URI:latest
      - echo "Build completed successfully"

artifacts:
  files:
    - app.py
    - Dockerfile
  discard-paths: yes
